# Generated by Django 4.2.10 on 2024-02-11 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_remove_post_user_post_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='project',
        ),
    ]
