# Generated by Django 4.2.10 on 2024-02-13 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0008_customuser_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='course',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='description_profile',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='specialization',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='telegram',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
