# Generated by Django 4.2.10 on 2024-02-20 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0009_customuser_course_customuser_description_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='color',
            field=models.IntegerField(null=True),
        ),
    ]
